// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Tim Dev Kompetisi",
            "url": "http://www.yourdomain.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/users/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperbarui data user tertentu berdasarkan ID. Hanya field yang dikirim yang akan diupdate.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Update User oleh Admin",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Target User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Data User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Data user berhasil diperbarui",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "error: User tidak ditemukan",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus user beserta semua relasi datanya di tabel images, samples, dan roles secara permanen (Clean up).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-users"
                ],
                "summary": "Hapus User Permanen (Clean Delete)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Target User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: User dan seluruh datanya berhasil dibersihkan",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error: Gagal total bantai user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentikasi user untuk mendapatkan token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "User Credentials",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid username or password",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Membuat akun user baru beserta penentuan Role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register User Baru",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/samples": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil semua log sampling dengan fitur filter ID User, ID Stasiun, dan rentang tanggal.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "samples"
                ],
                "summary": "List Riwayat Sampling (Admin/Asisten)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter per Petugas",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter per Stasiun",
                        "name": "station_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Format: YYYY-MM-DD",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Format: YYYY-MM-DD",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Petugas lapangan menginput nama sampel, kondisi, dan mengunggah beberapa foto dokumentasi sekaligus.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "samples"
                ],
                "summary": "Input Data Sampling \u0026 Upload Foto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Petugas",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID Stasiun",
                        "name": "station_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nama Sampel",
                        "name": "sample_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Catatan Kondisi Lapangan",
                        "name": "condition",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Multiple Images (Dokumentasi)",
                        "name": "images",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateSampleResponse"
                        }
                    },
                    "400": {
                        "description": "Error validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/samples/images/{id}": {
            "get": {
                "description": "Mengambil/menampilkan file fisik gambar berdasarkan ID gambar.",
                "produces": [
                    "image/*"
                ],
                "tags": [
                    "samples"
                ],
                "summary": "Lihat File Foto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Image ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/samples/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melihat detail lengkap satu data sampling beserta relasi User, Stasiun, dan Foto.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "samples"
                ],
                "summary": "Detail Data Sampling",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Sample ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sample"
                        }
                    }
                }
            }
        },
        "/samples/{id}/export": {
            "get": {
                "description": "Menghasilkan dokumen PDF resmi hasil sampling untuk diunduh.",
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "samples"
                ],
                "summary": "Export Laporan PDF",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Sample ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/stations": {
            "get": {
                "description": "Mengambil daftar lengkap stasiun untuk sinkronisasi data mobile app.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Ambil Semua Data Stasiun",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/stations/scan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memproses data hasil scan QR stasiun untuk pencatatan log petugas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Validasi Scan QR Stasiun",
                "parameters": [
                    {
                        "description": "Scan Data",
                        "name": "scan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ScanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ScanResponse"
                        }
                    },
                    "404": {
                        "description": "Station not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stations/validate-gps": {
            "post": {
                "description": "Memvalidasi jarak antara koordinat petugas (GPS HP) dengan koordinat stasiun asli menggunakan rumus Haversine. Maksimal toleransi 50 meter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations"
                ],
                "summary": "Validasi Lokasi GPS (Anti-Fraud)",
                "parameters": [
                    {
                        "description": "GPS \u0026 QR Data",
                        "name": "gps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GPSValidationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.GPSValidationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stations/{id}/qr": {
            "get": {
                "description": "Menghasilkan gambar QR Code (PNG) yang berisi data terenkripsi stasiun untuk discan petugas lapangan.",
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "stations-qr"
                ],
                "summary": "Generate QR Code Stasiun",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Station ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "error: Station not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stations/{id}/qr-data": {
            "get": {
                "description": "Melihat isi mentah (plaintext) dari QR Code stasiun. Berguna untuk testing integrasi mobile app (Parsing data).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations-qr"
                ],
                "summary": "Debug Data QR (Plaintext)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Station ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "error: Station not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stations/{id}/with-qr": {
            "get": {
                "description": "Mengambil data stasiun beserta URL langsung menuju gambar QR Code-nya.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stations-qr"
                ],
                "summary": "Detail Stasiun \u0026 Link QR",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Station ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "error: Station not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengunggah data sampling yang tersimpan secara lokal di perangkat mobile ke server (Offline-to-Online Synchronization).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "Sinkronisasi Data Offline",
                "parameters": [
                    {
                        "description": "Bulk Sync Data",
                        "name": "sync",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.SyncDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.SyncDataResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to sync sample/image",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.CreateSampleResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "sample_id": {
                    "type": "integer"
                }
            }
        },
        "controllers.GPSValidationRequest": {
            "type": "object",
            "properties": {
                "max_distance": {
                    "description": "Optional, default 50m",
                    "type": "number"
                },
                "qr_data": {
                    "type": "string"
                },
                "user_lat": {
                    "type": "number"
                },
                "user_lng": {
                    "type": "number"
                }
            }
        },
        "controllers.GPSValidationResponse": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "message": {
                    "type": "string"
                },
                "recommended_radius": {
                    "type": "number"
                },
                "station": {
                    "description": "Ganti dari fiber.Map ke ini",
                    "type": "object",
                    "additionalProperties": true
                },
                "station_lat": {
                    "type": "number"
                },
                "station_lng": {
                    "type": "number"
                },
                "user_lat": {
                    "type": "number"
                },
                "user_lng": {
                    "type": "number"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "controllers.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "controllers.RegisterRequest": {
            "type": "object",
            "properties": {
                "confirm_password": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.RegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "controllers.ScanRequest": {
            "type": "object",
            "properties": {
                "coordinate": {
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                }
            }
        },
        "controllers.ScanResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "controllers.SyncDataRequest": {
            "type": "object",
            "properties": {
                "samples": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.SyncSampleRequest"
                    }
                }
            }
        },
        "controllers.SyncDataResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "synced_images": {
                    "type": "integer"
                },
                "synced_samples": {
                    "type": "integer"
                }
            }
        },
        "controllers.SyncImageRequest": {
            "type": "object",
            "properties": {
                "image_path": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "controllers.SyncSampleRequest": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.SyncImageRequest"
                    }
                },
                "sample_name": {
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "controllers.UpdateRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.Image": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "image_id": {
                    "type": "integer"
                },
                "image_path": {
                    "type": "string"
                },
                "sample_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Role": {
            "type": "object",
            "properties": {
                "role_id": {
                    "type": "integer"
                },
                "role_name": {
                    "type": "string"
                }
            }
        },
        "models.Sample": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Image"
                    }
                },
                "is_reviewed": {
                    "type": "boolean"
                },
                "sample_id": {
                    "type": "integer"
                },
                "sample_name": {
                    "type": "string"
                },
                "station": {
                    "$ref": "#/definitions/models.Station"
                },
                "station_id": {
                    "type": "integer"
                },
                "user": {
                    "description": "Relations (INI YANG SUDAH BENAR)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Station": {
            "type": "object",
            "properties": {
                "coordinate": {
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                },
                "station_name": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Role"
                    }
                },
                "samples": {
                    "description": "Relations",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Sample"
                    }
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token dengan format: Bearer \u003cyour_token\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API Sistem Sampling Digital",
	Description:      "Dokumentasi API untuk pengumpulan sampel lapangan, validasi GPS, dan sinkronisasi data offline.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
